tmpdir: "/Users/mfansler/scratch/hcl-utrome"

metadataFile: "metadata/hcl-sra-run-table.csv"
annotsFile: "metadata/hcl-cell-annots.clean.tsv.gz"
samplesFile: "metadata/hcl-samples.txt"
celltypesSamplesFile: "metadata/hcl-celltypes-samples.csv"

adaptersFile: "microwell_seq_adapters.txt"
barcodeRegex: '(?P<cell_1>.{6})(?P<discard_1>CGACTCACTACAGGG){s<=1}(?P<cell_2>.{6})(?P<discard_2>TCGGTGACACGATCG){s<=1}(?P<cell_3>.{6})(?P<umi_1>.{6})(?P<discard_3>T{12}){s<=2}.*'

minReadLength: 21

hisatIndex: "/data/mayrc/db/hg38/grch38_snp_tran/genome_snp_tran"
chromSizes: "metadata/grch38.chrom.sizes"

radiusGENCODE: 20
radiusPAS: 20

extUTR3: 5000
extUTR5: 1000

epsilon:
  - 30

threshold:
  - 5

gencodeVersion:
  - 42
  - 44
  - 48

polyASiteTPM:
  - 3

minLikelihood:
  - 0.9999

width:
  - 500

mergeDistance:
  - 200
