tmpdir: "/fscratch/fanslerm"

metadataFile: "metadata/hcl-sra-run-table.csv"

adaptersFile: "microwell_seq_adapters.txt"
barcodeRegex: '(?P<cell_1>.{6})(?P<discard_1>CGACTCACTACAGGG){s<=1}(?P<cell_2>.{6})(?P<discard_2>TCGGTGACACGATCG){s<=1}(?P<cell_3>.{6})(?P<umi_1>.{6})(?P<discard_3>T{12}){s<=2}.*'

minReadLength: 21

hisatIndex: "/data/mayrc/db/hg38/grch38_snp_tran/genome_snp_tran"

radiusGENCODE: 20
radiusPAS: 20

extUTR3: 5000
extUTR5: 1000
